language: ruby

matrix:
  include:
  - rvm: 2.4.1
    env:
      - LABEL=unit_tests
  - rvm: 2.4.3
    env:
      - LABEL=unit_tests
  - rvm: 2.5.0
    env:
      - LABEL=unit_tests
  - rvm: 2.6.0
    env:
      - LABEL=unit_tests

before_install:
  - gem update --system
  - gem update --remote bundler

script:
  - bundle install
  - RACK_ENV=test ./bin/seed
  - bundle exec rspec

services:
  - mongodb
